[package]
name = "sevensegment-parser"
description = "A small library for parsing SSDs. Intended for personal use only & not maintained."
version = "0.1.0"
edition = "2021"

[[example]]
name = "main"

[dependencies]